//! Multi-IDE Config Export — one ProjectConfig → all major AI IDE rule files.
//!
//! Reads the project's existing AI-context sources (`CLAUDE.md`, `AGENTS.md`,
//! and `.cortex/rules/*.md`) and writes equivalent rule files for the IDEs
//! the user opts in to. Each format is independent so users can pick "just
//! Cursor" or "all of them" from the UI checklist.
//!
//! Output paths (relative to `project_root` unless noted):
//!  - `cursor`   → `.cursor/rules/cortex.mdc`               (YAML frontmatter)
//!  - `windsurf` → `.windsurfrules`                         (plain text)
//!  - `cline`    → `.clinerules/cortex.md`                  (markdown)
//!  - `copilot`  → `.github/copilot-instructions.md`        (markdown)
//!  - `codex`    → `~/.codex/AGENTS.md`                     (user home — global)
//!
//! Returns the list of files actually written plus structured skip reasons,
//! so the frontend can render a per-format status without re-running.

use serde::{Deserialize, Serialize};
use std::fs;
use std::path::{Path, PathBuf};

/// All format identifiers the backend understands. The frontend sends a
/// subset of these strings; anything we don't recognise is reported as a
/// skip rather than failing the whole call.
const KNOWN_FORMATS: &[&str] = &["cursor", "windsurf", "cline", "copilot", "codex"];

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExportSkip {
    pub path: String,
    pub reason: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExportResult {
    pub written: Vec<PathBuf>,
    pub skipped: Vec<ExportSkip>,
}

/// Loads `CLAUDE.md` + `AGENTS.md` + each `.cortex/rules/*.md` body into a
/// single normalised markdown blob. Section headers identify the source so
/// downstream IDEs can render or fold them. Missing files are silently
/// skipped — a fresh project with no docs still exports a (minimal) shell.
fn collect_source(project_root: &Path) -> String {
    let mut out = String::new();
    out.push_str("# Cortex — Merged AI Instructions\n\n");
    out.push_str(
        "_Auto-generated by Cortex. Source: `CLAUDE.md`, `AGENTS.md`, `.cortex/rules/*.md`._\n\n",
    );

    let claude_md = project_root.join("CLAUDE.md");
    if let Ok(body) = fs::read_to_string(&claude_md) {
        out.push_str("## CLAUDE.md\n\n");
        out.push_str(body.trim_end());
        out.push_str("\n\n");
    }

    let agents_md = project_root.join("AGENTS.md");
    if let Ok(body) = fs::read_to_string(&agents_md) {
        out.push_str("## AGENTS.md\n\n");
        out.push_str(body.trim_end());
        out.push_str("\n\n");
    }

    let rules_dir = project_root.join(".cortex").join("rules");
    if rules_dir.is_dir() {
        let mut rule_files: Vec<PathBuf> = Vec::new();
        if let Ok(entries) = fs::read_dir(&rules_dir) {
            for e in entries.flatten() {
                let p = e.path();
                let Some(name) = p.file_name().and_then(|n| n.to_str()) else { continue };
                if !p.is_file() {
                    continue;
                }
                if !name.ends_with(".md") && !name.ends_with(".mdc") {
                    continue;
                }
                rule_files.push(p);
            }
        }
        rule_files.sort();
        for rule in rule_files {
            if let Ok(body) = fs::read_to_string(&rule) {
                let name = rule
                    .file_name()
                    .and_then(|n| n.to_str())
                    .unwrap_or("rule.md");
                out.push_str(&format!("## .cortex/rules/{name}\n\n"));
                out.push_str(body.trim_end());
                out.push_str("\n\n");
            }
        }
    }

    out
}

/// Writes `body` to `path`, creating parent dirs first. Returns Ok on
/// success; the caller is responsible for tracking skip metadata.
fn write_file(path: &Path, body: &str) -> Result<(), String> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("mkdir {}: {e}", parent.display()))?;
    }
    fs::write(path, body).map_err(|e| format!("write {}: {e}", path.display()))
}

/// Builds a Cursor `.mdc` body with the YAML frontmatter Cursor expects. We
/// default to `alwaysApply: true` so the rules load on every turn; users can
/// edit the file by hand afterward to scope it more tightly.
fn render_cursor(body: &str) -> String {
    let mut out = String::with_capacity(body.len() + 64);
    out.push_str("---\n");
    out.push_str("description: Cortex-merged AI instructions for this repo\n");
    out.push_str("alwaysApply: true\n");
    out.push_str("---\n\n");
    out.push_str(body);
    out
}

/// `.windsurfrules` is plain text — strip the markdown shell line that the
/// other formats use as a heading so Windsurf doesn't show stray `#`s.
fn render_windsurf(body: &str) -> String {
    body.to_string()
}

fn render_cline(body: &str) -> String {
    body.to_string()
}

fn render_copilot(body: &str) -> String {
    body.to_string()
}

fn render_codex(body: &str) -> String {
    body.to_string()
}

/// Resolve where each format writes. `cursor`/`windsurf`/`cline`/`copilot`
/// are project-local; `codex` writes to `~/.codex/AGENTS.md` because that's
/// where the Codex CLI looks for its global memory.
fn target_path(format: &str, project_root: &Path) -> Option<PathBuf> {
    match format {
        "cursor" => Some(project_root.join(".cursor").join("rules").join("cortex.mdc")),
        "windsurf" => Some(project_root.join(".windsurfrules")),
        "cline" => Some(project_root.join(".clinerules").join("cortex.md")),
        "copilot" => Some(
            project_root
                .join(".github")
                .join("copilot-instructions.md"),
        ),
        "codex" => dirs::home_dir().map(|h| h.join(".codex").join("AGENTS.md")),
        _ => None,
    }
}

/// Render `format` from `source` into the appropriate textual form. Returns
/// `None` for unknown identifiers so the caller can surface a skip reason.
fn render(format: &str, source: &str) -> Option<String> {
    match format {
        "cursor" => Some(render_cursor(source)),
        "windsurf" => Some(render_windsurf(source)),
        "cline" => Some(render_cline(source)),
        "copilot" => Some(render_copilot(source)),
        "codex" => Some(render_codex(source)),
        _ => None,
    }
}

/// Tauri command: export the active project's merged context to one or more
/// IDE rule files. `formats` is opt-in — empty input yields an empty result
/// rather than exporting everything (avoids surprising users).
#[tauri::command]
pub async fn export_ide_configs(
    project_root: String,
    formats: Vec<String>,
) -> Result<ExportResult, String> {
    let root = PathBuf::from(&project_root);
    if !root.is_dir() {
        return Err(format!("not a directory: {project_root}"));
    }

    let source = collect_source(&root);
    let mut written: Vec<PathBuf> = Vec::new();
    let mut skipped: Vec<ExportSkip> = Vec::new();

    for raw in formats {
        let fmt = raw.trim().to_lowercase();
        if fmt.is_empty() {
            continue;
        }
        if !KNOWN_FORMATS.contains(&fmt.as_str()) {
            skipped.push(ExportSkip {
                path: raw,
                reason: "unknown format".into(),
            });
            continue;
        }
        let Some(path) = target_path(&fmt, &root) else {
            skipped.push(ExportSkip {
                path: fmt.clone(),
                reason: "could not resolve target path (no home dir?)".into(),
            });
            continue;
        };
        let Some(rendered) = render(&fmt, &source) else {
            skipped.push(ExportSkip {
                path: path.display().to_string(),
                reason: "no renderer for format".into(),
            });
            continue;
        };
        match write_file(&path, &rendered) {
            Ok(()) => written.push(path),
            Err(e) => skipped.push(ExportSkip {
                path: path.display().to_string(),
                reason: e,
            }),
        }
    }

    Ok(ExportResult { written, skipped })
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn unknown_formats_are_skipped_not_errored() {
        let td = TempDir::new().unwrap();
        let root = td.path();
        let res = tauri::async_runtime::block_on(export_ide_configs(
            root.display().to_string(),
            vec!["nope".into()],
        ))
        .unwrap();
        assert!(res.written.is_empty());
        assert_eq!(res.skipped.len(), 1);
        assert_eq!(res.skipped[0].reason, "unknown format");
    }

    #[test]
    fn writes_cursor_with_frontmatter() {
        let td = TempDir::new().unwrap();
        let root = td.path();
        fs::write(root.join("CLAUDE.md"), "# Project Rules\n\nBe helpful.\n").unwrap();
        let res = tauri::async_runtime::block_on(export_ide_configs(
            root.display().to_string(),
            vec!["cursor".into()],
        ))
        .unwrap();
        assert_eq!(res.written.len(), 1);
        let body = fs::read_to_string(&res.written[0]).unwrap();
        assert!(body.starts_with("---\n"));
        assert!(body.contains("alwaysApply: true"));
        assert!(body.contains("Be helpful."));
    }
}
